version: "2"

services:
  bot:
    build:
      context: .
      dockerfile: Bot.dockerfile
    restart: always

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: bigbrother
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    restart: always